### PR TITLE
add check for deps packages

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Signed-off-by: Ryan P.C. McQuen <ryan.q@linux.com>

### CODE REVIEW

**Comment by Thorn-Inurcide** [comment]
I can't use the package check though though it is nice, Cuz if I recompile
and want to reinstall something it will just tell me the package exist
already and wont do it =/
I'll leave the request open though, After the New Slackware Stable comes
out, I'll merge it when I make an actual Release, right now I am messing
around with the scripts too much, trying to figure out how to get the most
features out of it

**Comment by ryanpcmcquen** [comment]
What if we put in an override variable:

```shell
REBUILD=${REBUILD:-no}
```

Keep in mind that this check is only on `build-deps.sh`. I can understand that core is rebuilt/updated often, but are the dependencies rebuilt that often?

**Comment by Thorn-Inurcide** [comment]
A rebuild option would work, But like if i redo flags in tqt3, then
everything needs rebuilt for tde, so it's pretty important. plus the
possiblities of changes to source code with every release

**Comment by ryanpcmcquen** [comment]
How about an opt-out option for `REBUILD`?

**Comment by Thorn-Inurcide** [comment]
Yeah , As Long as I can rebuild them, it's cool however you want to go
about it. I see the REBUILD=yes ./build-deps.sh style
seems to be pretty common practice. Even if it's defaults to not rebuilding
them, and I have to specify it, I don't mind either way.

**Comment by ryanpcmcquen** [comment]
OK, I rebased the work so it is only one commit, default is `REBUILD=no`, but you can run as `REBUILD=yes` to force a rebuild of all dependencies. :+1:

**Pull request merged**
