### PR TITLE
Added Apps/koffice-i18n/koffice-i18n.SlackBuild

### PR DESCRIPTION
**Pull request by Ray-V**
and modified BUILD-TDE.sh - doesn't show me the diffs, but just added 
"Apps/koffice-i18n" "Internationalization files for koffice" ..... and put koffice above it.

Still trying to get GitHub to play nicely and only pull the commit(s) I want  - plan A almost worked, I'll try plan B next time.

### CODE REVIEW

**Comment by Ray-V** [comment]
No, I don't want to 'Merge branch 'master' into adding-koffice-i18n'   ff333e9

If you can't ignore that, cancel the pull request - I'm not messing around with this any more.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 

So you want me to cancel this pull request? I can do that it's all good

**Comment by Thorn-Inurcide** [comment]
Maybe I can't cancel that, I guess I can just ignore it though

**Comment by Thorn-Inurcide** [comment]
NVM i found it

**Comment by Ray-V** [comment]
Thanks - that's all back to square one now.
I'm going to set it all up again, I think I've got it right ...

**Pull request closed without merging**
